# Generated by Django 2.0.7 on 2018-08-25 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 25, 19, 44, 22, 266258)),
        ),
        migrations.AddField(
            model_name='historyofadminactivities',
            name='type',
            field=models.CharField(default='Add user', max_length=32),
        ),
        migrations.AddField(
            model_name='systemtransactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 25, 19, 44, 22, 266636)),
        ),
        migrations.AddField(
            model_name='systemtransactions',
            name='type',
            field=models.CharField(default='Charge', max_length=32),
        ),
    ]
