# Generated by Django 2.0.7 on 2018-08-26 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0002_auto_20180825_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 26, 4, 29, 16, 442459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 26, 4, 29, 16, 442840, tzinfo=utc)),
        ),
    ]
