# Generated by Django 2.0.7 on 2018-08-26 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0003_auto_20180826_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 26, 4, 33, 22, 931427, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 26, 4, 33, 22, 931847, tzinfo=utc)),
        ),
    ]
