# Generated by Django 2.0.7 on 2018-08-26 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0004_auto_20180826_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
