# Generated by Django 2.0.7 on 2018-08-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0005_auto_20180826_0434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryOfAdminActivities',
        ),
        migrations.DeleteModel(
            name='SystemTransactions',
        ),
    ]
