# Generated by Django 2.0.7 on 2018-08-26 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0006_auto_20180826_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfAdminActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Add user', max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SystemTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Charge', max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
