# Generated by Django 2.0.7 on 2018-08-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0007_historyofadminactivities_systemtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyofadminactivities',
            name='message',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
