# Generated by Django 2.0.7 on 2018-08-26 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0008_historyofadminactivities_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=models.DateField(default=datetime.datetime),
        ),
    ]
