# Generated by Django 2.0.7 on 2018-08-26 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0010_auto_20180826_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
    ]
