# Generated by Django 2.0.7 on 2018-08-26 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0012_auto_20180826_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 5, 4, 57, 47061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 26, 5, 4, 57, 47474, tzinfo=utc)),
        ),
    ]
