# Generated by Django 2.0.7 on 2018-08-26 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0013_auto_20180826_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 5, 5, 14, 876644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 5, 5, 14, 877124, tzinfo=utc)),
        ),
    ]
