# Generated by Django 2.0.7 on 2018-08-26 05:28

from django.db import migrations
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0015_auto_20180826_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
