# Generated by Django 2.0.7 on 2018-08-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0016_auto_20180826_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcredit',
            name='dollar_credit',
            field=models.IntegerField(default=0),
        ),
    ]
