# Generated by Django 2.0.7 on 2018-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0017_systemcredit_dollar_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='message',
            field=models.CharField(default='', max_length=512),
        ),
    ]
