# Generated by Django 2.0.3 on 2018-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0018_auto_20180826_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcredit',
            name='euro_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemcredit',
            name='pound_credit',
            field=models.IntegerField(default=0),
        ),
    ]
