# Generated by Django 2.0.7 on 2018-08-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0018_auto_20180826_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcredit',
            name='dollar_credit',
        ),
        migrations.RemoveField(
            model_name='systemcredit',
            name='rial_credit',
        ),
    ]
