# Generated by Django 2.0.7 on 2018-08-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0019_auto_20180826_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcredit',
            name='dollar_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemcredit',
            name='rial_credit',
            field=models.IntegerField(default=0),
        ),
    ]
