# Generated by Django 2.0.3 on 2018-08-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0019_auto_20180826_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcredit',
            name='dollar_credit',
        ),
        migrations.RemoveField(
            model_name='systemcredit',
            name='euro_credit',
        ),
        migrations.RemoveField(
            model_name='systemcredit',
            name='pound_credit',
        ),
        migrations.RemoveField(
            model_name='systemcredit',
            name='rial_credit',
        ),
    ]
