# Generated by Django 2.0.7 on 2018-08-27 06:28

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0019_contactusmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyofadminactivities',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='systemtransactions',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime.now),
        ),
    ]
