# Generated by Django 2.0.7 on 2018-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0020_auto_20180827_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcredit',
            name='euro_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemcredit',
            name='pound_credit',
            field=models.IntegerField(default=0),
        ),
    ]
