# Generated by Django 2.0.7 on 2018-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_admin', '0020_auto_20180827_1058'),
        ('KIA_admin', '0019_auto_20180826_2029'),
    ]

    operations = [
    ]
