# Generated by Django 2.0.7 on 2018-08-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_auth', '0005_auto_20180805_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
