# Generated by Django 2.0.3 on 2018-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiaservice',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='kiaservicefield',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
