# Generated by Django 2.0.7 on 2018-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_services', '0002_remove_kiatransaction_cost_in_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiatransaction',
            name='cost_in_currency',
            field=models.IntegerField(null=True),
        ),
    ]
