# Generated by Django 2.0.3 on 2018-08-11 12:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_services', '0002_auto_20180810_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='KIATransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('user_mail', models.EmailField(max_length=254, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Registered'), (2, 'Being done'), (3, 'Done'), (4, 'Failed')])),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='kiaservicefield',
            name='type',
            field=models.IntegerField(choices=[(1, 'BooleanField'), (2, 'CharField'), (3, 'CharField'), (4, 'TypedChoiceField'), (5, 'DateField'), (6, 'DateTimeField'), (7, 'DecimalField'), (8, 'DurationField '), (9, 'EmailField'), (10, 'FileField'), (11, 'FilePathField'), (13, 'IntegerField'), (14, 'MultipleChoiceField'), (15, 'TypedMultipleChoiceField'), (16, 'ComboField')]),
        ),
    ]
