# Generated by Django 2.0.3 on 2018-08-24 13:36

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_auth', '0006_profile_is_restricted'),
        ('kia_services', '0003_auto_20180811_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiatransaction',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='kiatransaction',
            name='user_mail',
        ),
        migrations.AddField(
            model_name='kiaservice',
            name='currency',
            field=models.IntegerField(choices=[(1, 'دلار'), (2, 'یورو'), (3, 'پوند')], default=1),
        ),
        migrations.AddField(
            model_name='kiaservice',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kiaservice',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kiaservice',
            name='variable_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kiaservicefield',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='assigned_emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_transactions', to='KIA_auth.Profile'),
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kia_services.KIAService'),
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transactions', to='KIA_auth.Profile'),
        ),
        migrations.AlterField(
            model_name='kiaservicefield',
            name='args',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='kiaservicefield',
            name='type',
            field=models.IntegerField(choices=[(1, 'فیلد صحیح و غلط'), (2, 'فیلد متنی'), (3, 'فیلد انتخاب یک گزینه'), (4, 'مبلغ ارزی'), (5, 'فیلد تاریخ'), (6, 'فیلد تاریخ و زمان'), (7, 'فیلد عدد اعشاری'), (9, 'فیلد ایمیل'), (10, 'فیلد فایل'), (13, 'فیلد عدد صحیح'), (14, 'فیلد انتخاب چند گزینه')]),
        ),
        migrations.AlterField(
            model_name='kiatransaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Registered'), (2, 'Being done'), (3, 'Done'), (4, 'Failed'), (5, 'Suspicious')]),
        ),
    ]
