# Generated by Django 2.0.7 on 2018-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_services', '0003_kiatransaction_cost_in_currency'),
        ('KIA_services', '0004_auto_20180827_0641'),
    ]

    operations = [
    ]
