# Generated by Django 2.0.3 on 2018-08-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_services', '0004_auto_20180824_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiatransaction',
            name='register_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='kiatransaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'ثبت شده'), (2, 'در حال انجام'), (3, 'تمام شده'), (4, 'رد شده'), (5, 'مشکوک')]),
        ),
    ]
