# Generated by Django 2.0.3 on 2018-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kia_services', '0004_auto_20180813_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiatransaction',
            name='user_mail',
        ),
        migrations.AddField(
            model_name='kiaservice',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kiaservicefield',
            name='type',
            field=models.IntegerField(choices=[(1, 'فیلد صحیح و غلط'), (2, 'فیلد متنی'), (3, 'فیلد انتخاب یک گزینه'), (5, 'فیلد تاریخ'), (6, 'فیلد تاریخ و زمان'), (7, 'فیلد عدد اعشاری'), (9, 'فیلد ایمیل'), (10, 'فیلد فایل'), (13, 'فیلد عدد صحیح'), (14, 'فیلد انتخاب چند گزینه')]),
        ),
    ]
