# Generated by Django 2.0.3 on 2018-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_services', '0005_auto_20180825_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiatransaction',
            name='cost_in_rial',
            field=models.IntegerField(null=True),
        ),
    ]
