# Generated by Django 2.0.3 on 2018-08-26 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_services', '0006_kiatransaction_cost_in_rial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiaservice',
            name='commission',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='cost_in_currency',
            field=models.IntegerField(null=True),
        ),
    ]
