# Generated by Django 2.0.3 on 2018-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kia_services', '0006_remove_kiaservice_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiaservice',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
