# Generated by Django 2.0.3 on 2018-08-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KIA_auth', '0006_profile_is_restricted'),
        ('kia_services', '0007_kiaservice_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiatransaction',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='kiatransaction',
            name='username',
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='assigned_emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_transactions', to='KIA_auth.Profile'),
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kia_services.KIAService'),
        ),
        migrations.AddField(
            model_name='kiatransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transactions', to='KIA_auth.Profile'),
        ),
    ]
